COACH_OUTPUT_SCHEMA = {
    "name": "teenmind_coach_output",
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "intent": {
                "type": "string",
                "enum": [
                    "anxiety", 
                    "stress", 
                    "sadness", 
                    "depression",
                    "loneliness",
                    "isolation",
                    "conflict", 
                    "anger",
                    "frustration",
                    "irritability",
                    "sleep", 
                    "insomnia",
                    "fatigue",
                    "self_esteem",
                    "body_image",
                    "identity_crisis",
                    "academic_pressure",
                    "test_anxiety",
                    "social_pressure",
                    "peer_pressure",
                    "bullying",
                    "social_anxiety",
                    "family_issues",
                    "relationship_issues",
                    "breakup",
                    "rejection",
                    "abandonment",
                    "grief",
                    "loss",
                    "overwhelm",
                    "burnout",
                    "boredom",
                    "apathy",
                    "emptiness",
                    "confusion",
                    "fear",
                    "panic",
                    "worry",
                    "guilt",
                    "shame",
                    "embarrassment",
                    "jealousy",
                    "envy",
                    "resentment",
                    "disappointment",
                    "hopelessness",
                    "helplessness",
                    "worthlessness",
                    "excitement",
                    "joy",
                    "contentment",
                    "relief",
                    "gratitude",
                    "curiosity",
                    "restlessness",
                    "impatience",
                    "casual"
                ]
            },
            "tone": {
                "type": "string",
                "enum": [
                    "calm", 
                    "overwhelmed", 
                    "panicky", 
                    "angry", 
                    "sad", 
                    "numb", 
                    "confused",
                    "hopeful",
                    "defeated",
                    "anxious",
                    "frustrated",
                    "worried",
                    "tired",
                    "exhausted",
                    "energetic",
                    "excited",
                    "scared",
                    "terrified",
                    "bitter",
                    "resentful",
                    "lonely",
                    "isolated",
                    "content",
                    "peaceful",
                    "joyful",
                    "grateful",
                    "relieved",
                    "nervous",
                    "tense",
                    "irritable",
                    "agitated",
                    "melancholic",
                    "numb",
                    "disconnected",
                    "empty",
                    "desperate",
                    "hopeless",
                    "ashamed",
                    "guilty",
                    "embarrassed",
                    "jealous",
                    "envious",
                    "insecure",
                    "vulnerable",
                    "defensive",
                    "restless",
                    "impatient",
                    "apathetic",
                    "indifferent",
                    "other"
                ]
            },
            "risk_level": {
                "type": "string",
                "enum": ["low", "medium", "high"]
            },
            "should_offer_skill": {"type": "boolean"},
            "assistant_message": {"type": "string"}
        },
        "required": ["intent", "tone", "risk_level", "should_offer_skill", "assistant_message"]
    },
    "strict": True
}